spring:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/employee_portal
      username: root
      password: root
    jpa:
      hibernate.ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
    devtools.livereload.enabled: false